# Word2Vec implementation

## Word Embeddings 

### To do:
1. Sentences
2. One hot representation
3. onehot represenation - emdedding layer keras to form matrix
4. embedding matrix, dims = 10, voc_size=100

In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [3]:
voc_size = 100

## one hot representation

In [4]:
onehot_rep = [one_hot(word,voc_size) for word in sent]
print(onehot_rep)

[[22, 72, 4, 57], [22, 72, 4, 55], [22, 80, 4, 18], [23, 26, 18, 43, 39], [23, 26, 18, 43, 32], [21, 22, 32, 4, 82], [96, 16, 44, 43]]


In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length = 6
embedded_docs = pad_sequences(onehot_rep, padding='pre', maxlen=sent_length)

In [8]:
print(embedded_docs)

[[ 0  0 22 72  4 57]
 [ 0  0 22 72  4 55]
 [ 0  0 22 80  4 18]
 [ 0 23 26 18 43 39]
 [ 0 23 26 18 43 32]
 [ 0 21 22 32  4 82]
 [ 0  0 96 16 44 43]]


In [9]:
dim = 10
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse') # mse: mean square error

Metal device set to: Apple M1


2023-04-08 11:12:30.376843: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-04-08 11:12:30.377463: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 6, 10)             1000      
                                                                 
Total params: 1,000
Trainable params: 1,000
Non-trainable params: 0
_________________________________________________________________


In [11]:
print(model.predict(embedded_docs))

2023-04-08 11:12:30.563552: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


1/1 [==============================] - 0s 119ms/step
[[[ 0.0196651   0.01774057  0.01473716  0.01228346  0.0208907
   -0.03213916  0.00725083 -0.0062057   0.00702175 -0.03996366]
  [ 0.0196651   0.01774057  0.01473716  0.01228346  0.0208907
   -0.03213916  0.00725083 -0.0062057   0.00702175 -0.03996366]
  [ 0.00608636 -0.00623165 -0.04122325 -0.01319671 -0.0051131
    0.03199809 -0.00809094 -0.02704667  0.04468947  0.02160177]
  [-0.04882992 -0.00268437  0.04731997 -0.03280808  0.03566771
   -0.04778253  0.03740141 -0.02505186 -0.03663842  0.02226534]
  [-0.00578365 -0.02893348 -0.04561713  0.02196502  0.0395289
   -0.03152865  0.03600262 -0.03823272 -0.0260758  -0.02168975]
  [-0.01708166 -0.02317803 -0.01435928 -0.03938144 -0.04561948
   -0.04702109  0.01442081  0.01981676 -0.01073205  0.00452109]]

 [[ 0.0196651   0.01774057  0.01473716  0.01228346  0.0208907
   -0.03213916  0.00725083 -0.0062057   0.00702175 -0.03996366]
  [ 0.0196651   0.01774057  0.01473716  0.01228346  0.0208907

2023-04-08 11:12:30.638367: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [12]:
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

# define documents
docs = ['Well done!',
        'Good work',
        'Great effort',
        'nice work',
        'Excellent!',
        'Weak',
        'Poor effort!',
        'not good',
        'poor work', 
        'Could have done better.']

# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])

# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# summarize the model
print(model.summary())

# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)

# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

[[20, 16], [25, 3], [38, 43], [1, 3], [18], [44], [3, 43], [43, 25], [3, 3], [45, 15, 16, 38]]
[[20 16  0  0]
 [25  3  0  0]
 [38 43  0  0]
 [ 1  3  0  0]
 [18  0  0  0]
 [44  0  0  0]
 [ 3 43  0  0]
 [43 25  0  0]
 [ 3  3  0  0]
 [45 15 16 38]]
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 4, 8)              400       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


2023-04-08 11:12:31.022726: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Accuracy: 100.000000


2023-04-08 11:12:31.662555: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


## Word2vec using pretrained gensim

In [13]:
!pip install gensim

In [14]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [15]:
import gensim.downloader as api

In [16]:
wv = api.load('word2vec-google-news-300')
vec_king = wv['king']

In [17]:
vec_king.shape

(300,)

In [18]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

## word2vec from scratch

In [85]:
import pandas as pd
messages = pd.read_csv('spam.csv', encoding="windows-1250")

In [86]:
messages

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ě_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [87]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [88]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/ammaarkhan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [89]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['v2'][i])
    review = review.lower()
    review = review.split()
    
    review = [lemmatizer.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [90]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [91]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [92]:
words =[]
for sent in corpus:
    sent_token = sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [93]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [94]:
import gensim

In [95]:
# training word2vec from scratch
model=gensim.models.Word2Vec(words)

In [96]:
# get all the vocabulary size
model.wv.index_to_key

['you',
 'to',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'be',
 'if',
 'will',
 'ur',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'time',
 'good',
 'then',
 'am',
 'got',
 'wa',
 'there',
 'he',
 'text',
 'only',
 'love',
 'want',
 'send',
 'txt',
 'need',
 'one',
 'today',
 'going',
 'by',
 'home',
 'don',
 'about',
 'stop',
 'she',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'our',
 'think',
 'dont',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'they',
 'any',
 'her',
 'pls',
 'ha',
 'please',
 'co',
 'did',
 'msg',
 'been',
 'min',
 'an',
 'some',
 'dear',
 'make',
 'here',
 'night',
 'message',
 'who',
 'say',
 'well',
 're',
 'where',
 'thing',
 'much',
 'grea

In [97]:
model.corpus_count

5569

In [98]:
model.epochs

5

In [99]:
model.wv.similar_by_word('good')

[('happy', 0.9987919330596924),
 ('day', 0.99876868724823),
 ('my', 0.9986880421638489),
 ('morning', 0.9986672401428223),
 ('where', 0.998641848564148),
 ('wa', 0.9986217021942139),
 ('hope', 0.998591959476471),
 ('great', 0.9985904693603516),
 ('well', 0.9985381960868835),
 ('dear', 0.9984665513038635)]

In [100]:
def avg_word2vec(doc):
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

In [101]:
from tqdm import tqdm

In [102]:
x=[]
for i in tqdm(range(len(words))):
    print("hello",i)
    x.append(avg_word2vec(words[i]))

  0%|                                                  | 0/5569 [00:00<?, ?it/s]/Users/ammaarkhan/opt/anaconda3/envs/ml/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/ammaarkhan/opt/anaconda3/envs/ml/lib/python3.10/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
 28%|██████████▌                          | 1583/5569 [00:00<00:00, 7974.90it/s]

hello 0
hello 1
hello 2
hello 3
hello 4
hello 5
hello 6
hello 7
hello 8
hello 9
hello 10
hello 11
hello 12
hello 13
hello 14
hello 15
hello 16
hello 17
hello 18
hello 19
hello 20
hello 21
hello 22
hello 23
hello 24
hello 25
hello 26
hello 27
hello 28
hello 29
hello 30
hello 31
hello 32
hello 33
hello 34
hello 35
hello 36
hello 37
hello 38
hello 39
hello 40
hello 41
hello 42
hello 43
hello 44
hello 45
hello 46
hello 47
hello 48
hello 49
hello 50
hello 51
hello 52
hello 53
hello 54
hello 55
hello 56
hello 57
hello 58
hello 59
hello 60
hello 61
hello 62
hello 63
hello 64
hello 65
hello 66
hello 67
hello 68
hello 69
hello 70
hello 71
hello 72
hello 73
hello 74
hello 75
hello 76
hello 77
hello 78
hello 79
hello 80
hello 81
hello 82
hello 83
hello 84
hello 85
hello 86
hello 87
hello 88
hello 89
hello 90
hello 91
hello 92
hello 93
hello 94
hello 95
hello 96
hello 97
hello 98
hello 99
hello 100
hello 101
hello 102
hello 103
hello 104
hello 105
hello 106
hello 107
hello 108
hello 109
hello 110


 59%|█████████████████████▊               | 3286/5569 [00:00<00:00, 8370.31it/s]

hello 1595
hello 1596
hello 1597
hello 1598
hello 1599
hello 1600
hello 1601
hello 1602
hello 1603
hello 1604
hello 1605
hello 1606
hello 1607
hello 1608
hello 1609
hello 1610
hello 1611
hello 1612
hello 1613
hello 1614
hello 1615
hello 1616
hello 1617
hello 1618
hello 1619
hello 1620
hello 1621
hello 1622
hello 1623
hello 1624
hello 1625
hello 1626
hello 1627
hello 1628
hello 1629
hello 1630
hello 1631
hello 1632
hello 1633
hello 1634
hello 1635
hello 1636
hello 1637
hello 1638
hello 1639
hello 1640
hello 1641
hello 1642
hello 1643
hello 1644
hello 1645
hello 1646
hello 1647
hello 1648
hello 1649
hello 1650
hello 1651
hello 1652
hello 1653
hello 1654
hello 1655
hello 1656
hello 1657
hello 1658
hello 1659
hello 1660
hello 1661
hello 1662
hello 1663
hello 1664
hello 1665
hello 1666
hello 1667
hello 1668
hello 1669
hello 1670
hello 1671
hello 1672
hello 1673
hello 1674
hello 1675
hello 1676
hello 1677
hello 1678
hello 1679
hello 1680
hello 1681
hello 1682
hello 1683
hello 1684
hello 1685

 89%|████████████████████████████████▉    | 4962/5569 [00:00<00:00, 8357.56it/s]

hello 3303
hello 3304
hello 3305
hello 3306
hello 3307
hello 3308
hello 3309
hello 3310
hello 3311
hello 3312
hello 3313
hello 3314
hello 3315
hello 3316
hello 3317
hello 3318
hello 3319
hello 3320
hello 3321
hello 3322
hello 3323
hello 3324
hello 3325
hello 3326
hello 3327
hello 3328
hello 3329
hello 3330
hello 3331
hello 3332
hello 3333
hello 3334
hello 3335
hello 3336
hello 3337
hello 3338
hello 3339
hello 3340
hello 3341
hello 3342
hello 3343
hello 3344
hello 3345
hello 3346
hello 3347
hello 3348
hello 3349
hello 3350
hello 3351
hello 3352
hello 3353
hello 3354
hello 3355
hello 3356
hello 3357
hello 3358
hello 3359
hello 3360
hello 3361
hello 3362
hello 3363
hello 3364
hello 3365
hello 3366
hello 3367
hello 3368
hello 3369
hello 3370
hello 3371
hello 3372
hello 3373
hello 3374
hello 3375
hello 3376
hello 3377
hello 3378
hello 3379
hello 3380
hello 3381
hello 3382
hello 3383
hello 3384
hello 3385
hello 3386
hello 3387
hello 3388
hello 3389
hello 3390
hello 3391
hello 3392
hello 3393

100%|█████████████████████████████████████| 5569/5569 [00:00<00:00, 8248.32it/s]

hello 5015
hello 5016
hello 5017
hello 5018
hello 5019
hello 5020
hello 5021
hello 5022
hello 5023
hello 5024
hello 5025
hello 5026
hello 5027
hello 5028
hello 5029
hello 5030
hello 5031
hello 5032
hello 5033
hello 5034
hello 5035
hello 5036
hello 5037
hello 5038
hello 5039
hello 5040
hello 5041
hello 5042
hello 5043
hello 5044
hello 5045
hello 5046
hello 5047
hello 5048
hello 5049
hello 5050
hello 5051
hello 5052
hello 5053
hello 5054
hello 5055
hello 5056
hello 5057
hello 5058
hello 5059
hello 5060
hello 5061
hello 5062
hello 5063
hello 5064
hello 5065
hello 5066
hello 5067
hello 5068
hello 5069
hello 5070
hello 5071
hello 5072
hello 5073
hello 5074
hello 5075
hello 5076
hello 5077
hello 5078
hello 5079
hello 5080
hello 5081
hello 5082
hello 5083
hello 5084
hello 5085
hello 5086
hello 5087
hello 5088
hello 5089
hello 5090
hello 5091
hello 5092
hello 5093
hello 5094
hello 5095
hello 5096
hello 5097
hello 5098
hello 5099
hello 5100
hello 5101
hello 5102
hello 5103
hello 5104
hello 5105

In [103]:
x

[array([-0.16022442,  0.19445969,  0.11393762,  0.11342052,  0.05830803,
        -0.42035496,  0.23433033,  0.57353157, -0.2300494 , -0.17369846,
        -0.15080716, -0.4576102 , -0.07645632,  0.1141977 ,  0.09647318,
        -0.16280843,  0.06821453, -0.30939814, -0.0210489 , -0.46005383,
         0.22331038,  0.21987346,  0.15576768, -0.12974215, -0.05175216,
         0.10991781, -0.2280772 , -0.24908441, -0.30682203,  0.1338937 ,
         0.30439588, -0.00190037,  0.11503973, -0.09990112, -0.1477425 ,
         0.29467934,  0.09125905, -0.23633596, -0.11932588, -0.51217765,
         0.04404916, -0.14637455, -0.05840488, -0.0417848 ,  0.17812347,
        -0.13830875, -0.16011241, -0.07799749,  0.13846189,  0.04775244,
         0.03916613, -0.21557154, -0.04023943, -0.00114362, -0.19909129,
         0.07903317,  0.16038884,  0.02851943, -0.34494755,  0.12397292,
         0.06432918,  0.00219101,  0.08634675, -0.03770396, -0.3060787 ,
         0.24137208,  0.10949493,  0.17221506, -0.3

In [104]:
len(x)

5569

In [105]:
# independant features
x_new = np.array(x)

/var/folders/08/1gttyz7x7yx93bdqyk3t_c4w0000gn/T/ipykernel_58315/733680791.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_new = np.array(x)


In [106]:
x_new.shape

(5569,)

In [107]:
x_new[0].shape

(100,)

In [108]:
# dependant features
# output features
y = messages[list(map(lambda x: len(x)>0 ,corpus))]
y=pd.get_dummies(y['v1'])
y=y.iloc[:,0].values

In [109]:
y.shape

(5569,)

In [110]:
# converting input feature into dataframe
df=pd.DataFrame()
for i in range(0,len(x)):
    df=df.append(pd.DataFrame(x[i].reshape(1,-1)),ignore_index=True)

/var/folders/08/1gttyz7x7yx93bdqyk3t_c4w0000gn/T/ipykernel_58315/127508848.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(pd.DataFrame(x[i].reshape(1,-1)),ignore_index=True)


In [111]:
df.head()

0         1         2         3         4         5         6   \
0 -0.160224  0.194460  0.113938  0.113421  0.058308 -0.420355  0.234330   
1 -0.145062  0.177897  0.100335  0.097074  0.048042 -0.369584  0.206053   
2 -0.171389  0.203816  0.160281  0.155615  0.075983 -0.457459  0.216590   
3 -0.232508  0.266058  0.141504  0.149220  0.072125 -0.578013  0.324190   
4 -0.200775  0.219398  0.132675  0.126874  0.076254 -0.490126  0.274068   

         7         8         9   ...        90        91        92        93  \
0  0.573532 -0.230049 -0.173698  ...  0.380304  0.209917  0.012649  0.032461   
1  0.500726 -0.198043 -0.151337  ...  0.338249  0.172284  0.004163  0.034262   
2  0.629056 -0.251240 -0.200761  ...  0.402454  0.233224  0.002527  0.040817   
3  0.777687 -0.312769 -0.235082  ...  0.516131  0.265239  0.011168  0.058447   
4  0.659084 -0.270576 -0.204750  ...  0.438475  0.228486  0.014105  0.047482   

         94        95        96        97        98        99  
0  0.554936  0.307777  0.118596 -0.150032  0.114251 -0.033778  
1  0.481440  0.265334  0.099369 -0.142802  0.100686 -0.031412  
2  0.563688  0.330360  0.111057 -0.153595  0.092440 -0.029951  
3  0.763808  0.418107  0.159719 -0.218652  0.161329 -0.035207  
4  0.640761  0.358432  0.132237 -0.191464  0.134745 -0.033798  

[5 rows x 100 columns]

In [112]:
df.shape

(5569, 100)

In [113]:
df['Output']=y

In [114]:
df.head()

0         1         2         3         4         5         6  \
0 -0.160224  0.194460  0.113938  0.113421  0.058308 -0.420355  0.234330   
1 -0.145062  0.177897  0.100335  0.097074  0.048042 -0.369584  0.206053   
2 -0.171389  0.203816  0.160281  0.155615  0.075983 -0.457459  0.216590   
3 -0.232508  0.266058  0.141504  0.149220  0.072125 -0.578013  0.324190   
4 -0.200775  0.219398  0.132675  0.126874  0.076254 -0.490126  0.274068   

          7         8         9  ...        91        92        93        94  \
0  0.573532 -0.230049 -0.173698  ...  0.209917  0.012649  0.032461  0.554936   
1  0.500726 -0.198043 -0.151337  ...  0.172284  0.004163  0.034262  0.481440   
2  0.629056 -0.251240 -0.200761  ...  0.233224  0.002527  0.040817  0.563688   
3  0.777687 -0.312769 -0.235082  ...  0.265239  0.011168  0.058447  0.763808   
4  0.659084 -0.270576 -0.204750  ...  0.228486  0.014105  0.047482  0.640761   

         95        96        97        98        99  Output  
0  0.307777  0.118596 -0.150032  0.114251 -0.033778       1  
1  0.265334  0.099369 -0.142802  0.100686 -0.031412       1  
2  0.330360  0.111057 -0.153595  0.092440 -0.029951       0  
3  0.418107  0.159719 -0.218652  0.161329 -0.035207       1  
4  0.358432  0.132237 -0.191464  0.134745 -0.033798       1  

[5 rows x 101 columns]

In [115]:
df.dropna(inplace=True)

In [116]:
df.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
Output    0
Length: 101, dtype: int64

In [117]:
# final input data
x = df

In [118]:
x.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
Output    0
Length: 101, dtype: int64

In [119]:
y=df['Output']

In [120]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [121]:
X_train.head()

0         1         2         3         4         5         6  \
5176 -0.219289  0.250199  0.147401  0.148775  0.084384 -0.551305  0.304687   
4419 -0.156834  0.163575  0.110717  0.111132  0.072302 -0.376343  0.193760   
3817 -0.095151  0.259165  0.120672  0.099833 -0.042953 -0.497603  0.349282   
1141 -0.198752  0.229994  0.148373  0.146425  0.089917 -0.512034  0.264741   
2423 -0.224556  0.255452  0.147089  0.143347  0.076555 -0.553997  0.324552   

             7         8         9  ...        91        92        93  \
5176  0.739794 -0.302581 -0.233073  ...  0.253195  0.005618  0.050323   
4419  0.514003 -0.206831 -0.166962  ...  0.171459 -0.001416  0.038446   
3817  0.726709 -0.288348 -0.201239  ...  0.321912  0.087817  0.052235   
1141  0.694021 -0.279840 -0.219751  ...  0.244118  0.004220  0.047794   
2423  0.751642 -0.304062 -0.227399  ...  0.263936  0.017334  0.052919   

            94        95        96        97        98        99  Output  
5176  0.706909  0.399876  0.148619 -0.214963  0.153861 -0.037103       1  
4419  0.465230  0.266771  0.089357 -0.155703  0.095212 -0.017095       1  
3817  0.779076  0.423069  0.211892 -0.041748  0.133849 -0.130200       1  
1141  0.640767  0.367667  0.129923 -0.191466  0.126877 -0.033555       0  
2423  0.745177  0.415419  0.165464 -0.211505  0.166518 -0.041406       1  

[5 rows x 101 columns]

In [122]:
y_train

5176    1
4419    1
3817    1
1141    0
2423    1
       ..
1922    1
1037    1
676     1
1433    1
5065    1
Name: Output, Length: 4445, dtype: uint8

In [123]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [124]:
classifier.fit(X_train.values,y_train.values)

RandomForestClassifier()

In [125]:
y_pred=classifier.predict(X_test.values)

In [126]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))

0.9991007194244604


In [127]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00       127
           1       1.00      1.00      1.00       985

    accuracy                           1.00      1112
   macro avg       1.00      1.00      1.00      1112
weighted avg       1.00      1.00      1.00      1112



In [128]:
print(X_test)

             0         1         2         3         4         5         6  \
4688 -0.202110  0.206652  0.137930  0.136176  0.088800 -0.483565  0.257216   
685  -0.205143  0.217609  0.132084  0.127252  0.096807 -0.503065  0.280369   
5327 -0.194071  0.228388  0.142819  0.145920  0.075305 -0.508663  0.264025   
4617 -0.213649  0.255660  0.167800  0.157903  0.086028 -0.572337  0.313318   
3230 -0.223992  0.250878  0.144643  0.137365  0.080818 -0.560328  0.312215   
...        ...       ...       ...       ...       ...       ...       ...   
2144 -0.155286  0.191981  0.144621  0.141759  0.075325 -0.430130  0.204655   
5498 -0.138614  0.190858  0.137427  0.131697  0.054626 -0.410014  0.212401   
3532 -0.201173  0.300133  0.191465  0.202883  0.086409 -0.616598  0.316435   
4927 -0.241392  0.232866  0.134578  0.132292  0.094994 -0.553572  0.314787   
3352 -0.186541  0.210906  0.121319  0.119346  0.068062 -0.466442  0.262877   

             7         8         9  ...        91        92    